miniblog/miniblog/urls.py
from django.contrib import admin
from django.urls import path
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name="contact"),
    path('dashborad/', views.userdashborad, name="dashborad"),
    path('signup/', views.signup, name="signup"),
    path('login/', views.userlogin, name="login"),
    path('logout/', views.userlogout, name='logout'),
    path('addpost/', views.addpost, name="addpost"),
    path('update/<int:id>/', views.updatepost, name="update"),
    path('delete/<int:id>/', views.deletepost, name="delete"),
]

miniblog/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=150)
    desc = models.TextField()

miniblog/blog/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django import forms
from django.utils.translation import gettext, gettext_lazy as _
from .models import Post
class Signup(UserCreationForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class':'form-control cnt'}))
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput(attrs={'class':'form-control cnt'}))
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        labels = {'email':'Email'}
        widgets =  {'username':forms.TextInput(attrs={'class':'form-control cnt'}),
                    'first_name':forms.TextInput(attrs={'class':'form-control cnt'}),
                    'last_name':forms.TextInput(attrs={'class':'form-control cnt'}),
                    'email':forms.EmailInput(attrs={'class':'form-control cnt'})}


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'class':'form-control cnt', 'autofocus':True}))
    password = forms.CharField(label=_("Password"), strip=True,
                                widget=forms.PasswordInput(attrs={'autocomplete':'current-password', 
                                                                  'class':'form-control cnt'}))
    
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'desc']
        labels = {'title':'title', 'desc':'Description'}
        widgets =  {'title':forms.TextInput(attrs={'class':'form-control cnt'}),
                    'desc':forms.Textarea(attrs={'class':'form-control cnt'})}

miniblog/blog/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import Signup, LoginForm, PostForm
from django.contrib import messages
from .models import Post
from django.contrib.auth.models import Group
# from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def home(request):
    post = Post.objects.all()
    return render(request, 'blog/home.html', {"posts":post})

#about
def about(request):
    return render(request, "blog/about.html")

#contact
def contact(request):
    return render(request, "blog/contact.html")
   

#dashborad
def userdashborad(request):
    if request.user.is_authenticated:
        post = Post.objects.all()
        return render(request, 'blog/dashborad.html', {'posts':post})
    else:
        return HttpResponseRedirect('/login/')
    

#signup
def signup(request):
    if request.method=='POST':
        fm = Signup(request.POST)
        if fm.is_valid():
            messages.success(request, 'Your account created successfully')
            user = fm.save()
            group = Group.objects.get(name='Author')
            user.groups.add(group)
            return HttpResponseRedirect('/dashborad/')
    else: 
        fm = Signup()
    return render(request, 'blog/signup.html', {'form':fm})

#login
def userlogin(request):
    if not request.user.is_authenticated:
        if request.method=="POST":
            fm = LoginForm(request=request, data=request.POST)
            if fm.is_valid():
                uname = fm.cleaned_data['username']
                pw = fm.cleaned_data['password']
                valid_user = authenticate(username=uname, password=pw)
                if valid_user is not None:
                    login(request, valid_user)
                    messages.success(request, "Login successefully")
                    return HttpResponseRedirect(f'/dashborad/')
        else:
            fm = LoginForm()
        return render(request, 'blog/login.html', {"form":fm})
    else:
        return HttpResponseRedirect('/dashborad/')
#logout
def userlogout(request):
    if request.user.is_authenticated:
        logout(request) 
    return HttpResponseRedirect('/')

#add
def addpost(request):
    if request.user.is_authenticated:
        if request.method=="POST":
            fm = PostForm(request.POST)
            if fm.is_valid():
                fm.save()
                return HttpResponseRedirect('/dashborad/')
        else:
            fm = PostForm()
        return render(request, "blog/addpost.html", {"form":fm})
    else:
        return HttpResponseRedirect("/login/")
    

#update
def updatepost(request, id):
    if request.user.is_authenticated:
        if request.method=="POST":
            pi = Post.objects.get(pk=id)
            fm = PostForm(request.POST, instance=pi)
            if fm.is_valid():
                fm.save()
                return HttpResponseRedirect('/dashborad/')
        else:
            pi = Post.objects.get(pk=id)
            fm = PostForm(instance=pi)
        return render(request, "blog/update.html", {"form":fm})
    else:
        return HttpResponseRedirect("/login/")
    
def deletepost(request, id):
    if request.user.is_authenticated:
        if request.method=="POST":
            pi = Post.objects.get(pk=id)
            pi.delete()
        return HttpResponseRedirect("/dashborad/")
    else:
        return HttpResponseRedirect("/login/")

miniblog/blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">About Page</h3>
    <div class="col-md-6">
        <div class="h-100 p-5 bg-dark border rounded-3 jumbo-color">
          {% for fm in form %}
            {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} <br> <br>
            {% endfor %}
        </div>
      </div>
</div>
{% endblock content %}

miniblog/blog/templates/blog/addpost.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Add Blog</h3>
    <div class="col-md-10">
        <div class="h-100 p-5 bg-dark border rounded-3 jumbo-color">
          <form action="" method="post" novalidate>
            {% csrf_token %}
            {% for fm in form %}
            <div class="form-group">
            {{fm.label_tag}} {{fm}} <small class="text-warning">{{fm.errors|striptags}}</small> <br> <br>
            </div>
            {% endfor %}
            <button class="btn btn-primary" type="submit">POST</button>
        </form>
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                <p class="alert alert-denger my-3">{{error}}</p>
                {% endfor %}
            {% endif %}
        <br>
        <a href="{% url 'dashborad' %}" class="btn btn-warning">Back</a>

        </div>
    </div>
</div>

{% endblock content %}

miniblog/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="container-fluid bg-dark">
        {% include 'blog/navbar.html' %}
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% block msg %}
                {% endblock msg %}
            </div>
        </div>
        <div class="row">
            {% block side %}
            {% endblock side %}

            {% block content %}
            {% endblock content %}
        </div>
    </div>

    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/jquery' %}"></script>
</body>
</html>

miniblog/blog/templates/blog/contact.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-6">
    <h3 class="text-white my-5">Contact Page</h3>
    <form>
      <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input type="email" class="form-control cnt" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
      </div>
      <div class="form-group" >
        <label for="exampleFormControlTextarea1">Message</label>
        <textarea class="form-control cnt" id="exampleFormControlTextarea1" rows="3"></textarea>
      </div>
      <button type="submit" class="btn btn-primary my-5">Submit</button>
    </form>
</div>
{% endblock content %}

miniblog/blog/templates/blog/dashborad.html
{% extends 'blog/base.html' %}
{% load static %}
{% block msg %}
    {% if messages %}
            {% for message in messages %}
            <small {% if message.tags %} class="{{message.tags}}" {% endif %}>{{message}}</small>
            {% endfor %}
        {% endif %}
  {% endblock msg %}

  {% block content %}
  <div class="col-sm-10">
    <h3 class="text-white my-5">Dashborad Page</h3>
  <a href="{% url 'addpost' %}" class="btn btn-success">Add Post</a>
  <h4 class="text-center alert alert-info mt-3">Post Information</h4>
    <table class="table-hover table bg-white">
      <thead>
        <tr>
          <th scope="col" style="width:2%">ID</th>
          <th scope="col" style="width:28%">Title</th>
          <th scope="col" style="width:55%">Discription</th>
          <th scope="col" style="width:15%">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for post in posts %}
        <tr>
          <th scope="row">{{post.id}}</th>
          <td>{{post.title}}</td>
          <td>{{post.desc}}</td>
          <td class="text-center">
            <a href="{% url 'update' post.id %}" class="btn btn-warning btn-sm">Edit</a>
            {% if perms.blog.delete_post %}
            <form action="{% url 'delete' post.id %}" method="post">
              {% csrf_token %}
              <input type="submit" class="btn btn-danger btn-sm" value="Delete">
            </form>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    
  </div>
        
</div>
{% endblock content %}



miniblog/blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-12">
    <h3 class="text-white my-5">Home Page</h3>
    {% for post in posts %}
    <div class="col-md-6">
        <div class="h-100 p-5 bg-dark border rounded-3 jumbo-color">
            <h2 class="display-4 font-weight-bold">{{post.title}}</h2>
            <p class="lead">{{post.desc}}</p>
        </div>
      </div>
      <br>
      {% endfor %}
</div>
{% endblock content %}

miniblog/blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Login Page</h3>
    <div class="col-md-10">
        <div class="h-100 p-5 bg-dark border rounded-3 jumbo-color">
          <form action="" method="post" novalidate>
            {% csrf_token %}
            {% for fm in form %}
            <div class="form-group">
            {{fm.label_tag}} {{fm}} <small class="text-warning">{{fm.errors|striptags}}</small> <br> <br>
            </div>
            {% endfor %}
            <button class="btn btn-primary" type="submit">Login</button>
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                <p class="alert alert-denger my-3">{{error}}</p>
                {% endfor %}
            {% endif %}
        </form>
        <br>
        <a href="{% url 'signup' %}" class="btn btn-warning">Signup</a>
        </div>
      </div>
</div>
{% endblock content %}

miniblog/blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Mini Blog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dashborad' %}">Dashborad</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">LogOut</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'signup' %}">Signup</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}">Contact</a>
          </li>

          
        </ul>
      </div>
    </div>
  </nav>

miniblog/blog/templates/blog/signup.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
  <h3 class="text-white my-5">Signup Page</h3>
    <div class="col-md-10">
      <div class="h-100 p-5 bg-dark border rounded-3 jumbo-color">
          <form action="" method="POST" novalidate>
            {% csrf_token %}
            {% for fm in form %}
            <div class="form-group">
              {{fm.label_tag}} {{fm}}  <small class="text-warning">{{fm.errors|striptags}}</small> <br> <br>
            </div>
            {% endfor %}
            <button class="btn btn-primary" type="submit">Signup</button>
            {% if form.non_field_errors %}
              {% for error in form.non_field_errors %}
                <p class="alert alert-danger my-3">{{error}}</p>
              {% endfor %}
            {% endif %}
        </form>
        {% if messages %}
            {% for message in messages %}
            <small {% if message.tags %} class="{{message.tags}}" {% endif %}>{{message}}</small>
            {% endfor %}
        {% endif %}
        <br>
        <a href="{% url 'login' %}" class="btn btn-danger">Login</a>
      </div>
    </div>
</div>
{% endblock content %}

miniblog/blog/templates/blog/update.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Edit Post</h3>
    <div class="col-md-10">
        <div class="h-100 p-5 bg-dark border rounded-3 jumbo-color">
          <form action="" method="post" novalidate>
            {% csrf_token %}
            {% for fm in form %}
            <div class="form-group">
            {{fm.label_tag}} {{fm}} <small class="text-warning">{{fm.errors|striptags}}</small> <br> <br>
            </div>
            {% endfor %}
            <button class="btn btn-primary" type="submit">Update</button>
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                <p class="alert alert-denger my-3">{{error}}</p>
                {% endfor %}
            {% endif %}
        </form>
        <br>
        <a href="{% url 'dashborad' %}" class="btn btn-warning">Back</a>
        </div>
      </div>
{% endblock content %}
 